apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: settings-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: settings-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: settings-db-password
        version: latest
    - secretKey: OPENFGA_API_KEY
      remoteRef:
        key: openfga-preshared-key
        version: latest
    - secretKey: OPENFGA_PLATFORM_STORE_ID
      remoteRef:
        key: openfga-platform-store-id
        version: latest
