apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mp-content-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mp-content-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mp_content-db-password
        version: latest
