apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-connector-config
data:
  ENVIRONMENT: "production"
  GCP_PROJECT_ID: "tesserix-app"
  DB_HOST: "10.117.240.3"
  DB_PORT: "5432"
  DB_NAME: "mp_connector_db"
  DB_USER: "mp_connector_user"
  DB_SSLMODE: "require"
  SERVICE_AUTH_MODE: "mesh"
  PRODUCTS_SERVICE_URL: "http://mp-products.marketplace.svc.cluster.local"
  ORDERS_SERVICE_URL: "http://mp-orders.marketplace.svc.cluster.local"
  INVENTORY_SERVICE_URL: "http://mp-inventory.marketplace.svc.cluster.local"
  OPENFGA_URL: "http://openfga.shared.svc.cluster.local"
  OPENFGA_AUTH_MODE: "mesh"
  OPENFGA_MARKETPLACE_STORE_ID: "01KKNQENND85P9T01YCBCTRDHV"
