apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openfga-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: openfga-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENFGA_DATASTORE_URI
      remoteRef:
        key: openfga-db-uri
        version: latest
    - secretKey: OPENFGA_AUTHN_PRESHARED_KEYS
      remoteRef:
        key: openfga-preshared-key
        version: latest
