apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mp-staff-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mp-staff-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mp_staff-db-password
        version: latest
    - secretKey: OPENFGA_API_KEY
      remoteRef:
        key: openfga-preshared-key
        version: latest
