apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mp-approvals-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mp-approvals-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mp_approvals-db-password
        version: latest
