apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-payments-config
data:
  ENVIRONMENT: "production"
  GCP_PROJECT_ID: "tesserix-app"
  DB_HOST: "10.117.240.3"
  DB_PORT: "5432"
  DB_NAME: "mp_payments_db"
  DB_USER: "mp_payments_user"
  DB_SSLMODE: "require"
  SERVICE_AUTH_MODE: "mesh"
  OPENFGA_AUTH_MODE: "mesh"
  OPENFGA_URL: "http://openfga.shared.svc.cluster.local"
