apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: document-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: document-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: documents-db-password
        version: latest
