name = "tesserix-router"
main = "worker.js"
compatibility_date = "2026-03-01"
account_id = "6fe6e1aa18c221b529ce76c9631ba4e0"

[vars]
AUTH_BFF_URL = "PLACEHOLDER"
TESSERIX_HOME_URL = "PLACEHOLDER"
STOREFRONT_URL = "PLACEHOLDER"
MARKETPLACE_ONBOARDING_URL = "PLACEHOLDER"
BASE_DOMAIN = "mark8ly.com"

[[kv_namespaces]]
binding = "TENANT_ROUTES"
id = "1e14da3d238548fd8fa50982395d538d"

[[routes]]
pattern = "tesserix.app/*"
zone_name = "tesserix.app"

[[routes]]
pattern = "*.tesserix.app/*"
zone_name = "tesserix.app"

[[routes]]
pattern = "mark8ly.com/*"
zone_name = "mark8ly.com"

[[routes]]
pattern = "*.mark8ly.com/*"
zone_name = "mark8ly.com"
