apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mp-inventory-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mp-inventory-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mp_inventory-db-password
        version: latest
    - secretKey: INTERNAL_SERVICE_KEY
      remoteRef:
        key: shared-internal-service-key
        version: latest
