apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: tesserix
      auth:
        workloadIdentity:
          clusterLocation: asia-south1
          clusterName: tesserix-gke
          clusterProjectID: tesserix
          serviceAccountRef:
            name: eso-controller
            namespace: external-secrets
